version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mattia_portfolio
      POSTGRES_USER: mattia_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: